# Домашнее задание

Изучить, что такое собственный вектор
http://mathprofi.ru/sobstvennye_znachenija_i_sobstvennye_vektory.html

пример с картинкой в вики
https://ru.wikipedia.org/wiki/Собственный_вектор

Пример использования собственных векторов в Data Science - PCA (метод главных компонент, сжатие данных)

1) Сгенерировать две любые двумерные матрицы, один массив и один список, где заполненение происходит случайными элементами, 
- первая матрица размером 6 на 11 - a1
- вторая  матрица размером - 11 на 8 - a2
- массив 11 на 1 - a3
- список с кол-вом элементов = 11 - a4

In [2]:
import random
import numpy as np

In [9]:
a1 = np.random.randn(6, 11)
a2 = np.random.rand(11, 8) 
a3 = np.random.randint(0, 100, size = (11, 1))
a4 = [random.randint(-100, 100) for i in range(11)]

[[-2.3637578  -0.55524298  0.17311459 -0.60358799  1.1159429   1.9630548
   1.05930946  0.01637381  0.53631017  2.74984077 -0.72171605]
 [ 0.04240502  1.35974329 -1.04191841  0.76983528  0.04992593 -0.33888076
  -1.46264119 -0.23483539 -0.49786436 -0.51842684  0.8165408 ]
 [ 1.1057025  -0.71095741 -2.16273869  0.37095314 -0.10177794 -0.70738785
  -0.61840838  1.61860418 -0.15782131 -1.95762777  0.99023919]
 [-0.30887264  2.20102354  0.37000735  1.4246759   0.18456779  0.42207827
  -1.08829521 -0.89316797  0.32085933 -0.6392443  -0.85116364]
 [ 0.23205484  0.2235967   1.82476659 -1.59200476  1.18185635  1.05907527
   0.27551883  1.32176876  1.01587285 -1.95143311  0.224419  ]
 [-0.61249749  1.12755605  0.95768496  1.1635943   0.67633438  1.21692225
   0.1657133   1.190021    0.49185663 -0.6086149   0.76562986]]
[[0.66464258 0.41409063 0.68415056 0.38411951 0.62422812 0.01094484
  0.45403396 0.58748908]
 [0.06286964 0.997686   0.98029745 0.05963991 0.81829131 0.52523207
  0.80075853 0.40

2) Матрично умножить первую матрицу a1 на диагональную матрицу, созданную из списка a4 в задании 1

In [10]:
a1 @ np.diag(a4)

array([[ 184.37310867,  -17.21253231,   -7.09769829,   15.08969986,
         -74.76817398,  190.4163159 ,  -22.2454986 ,   -1.44089536,
         -45.58636412, -159.49076475,   49.07669116],
       [  -3.30759117,   42.15204196,   42.71865486,  -19.24588202,
          -3.34503764,  -32.87143411,   30.71546499,   20.6655144 ,
          42.31847096,   30.06875649,  -55.52477446],
       [ -86.24479535,  -22.03967959,   88.67228635,   -9.27382852,
           6.81912225,  -68.61662173,   12.98657591, -142.43716774,
          13.41481154,  113.54241081,  -67.33626506],
       [  24.09206619,   68.23172972,  -15.17030124,  -35.61689746,
         -12.36604223,   40.94159199,   22.85419939,   78.59878107,
         -27.27304333,   37.07616924,   57.8791277 ],
       [ -18.10027755,    6.9314978 ,  -74.81543032,   39.80011888,
         -79.18437529,  102.73030151,   -5.78589541, -116.31565083,
         -86.34919219,  113.1831201 ,  -15.26049213],
       [  47.77480387,   34.9542376 ,  -39.2650832

3) Матрично умножить транспонированную вторую матрицу a2 на массив a3

In [11]:
a2.T @ a3

array([[229.61494186],
       [379.32745838],
       [384.65819245],
       [329.58281289],
       [305.84682761],
       [150.74918226],
       [359.70111304],
       [187.80353673]])

4) Изменить размер первой матрицы, где она будет иметь 33 строки и 2 столбца 

In [12]:
a1.reshape(33, 2)

array([[-2.3637578 , -0.55524298],
       [ 0.17311459, -0.60358799],
       [ 1.1159429 ,  1.9630548 ],
       [ 1.05930946,  0.01637381],
       [ 0.53631017,  2.74984077],
       [-0.72171605,  0.04240502],
       [ 1.35974329, -1.04191841],
       [ 0.76983528,  0.04992593],
       [-0.33888076, -1.46264119],
       [-0.23483539, -0.49786436],
       [-0.51842684,  0.8165408 ],
       [ 1.1057025 , -0.71095741],
       [-2.16273869,  0.37095314],
       [-0.10177794, -0.70738785],
       [-0.61840838,  1.61860418],
       [-0.15782131, -1.95762777],
       [ 0.99023919, -0.30887264],
       [ 2.20102354,  0.37000735],
       [ 1.4246759 ,  0.18456779],
       [ 0.42207827, -1.08829521],
       [-0.89316797,  0.32085933],
       [-0.6392443 , -0.85116364],
       [ 0.23205484,  0.2235967 ],
       [ 1.82476659, -1.59200476],
       [ 1.18185635,  1.05907527],
       [ 0.27551883,  1.32176876],
       [ 1.01587285, -1.95143311],
       [ 0.224419  , -0.61249749],
       [ 1.12755605,

5) Получить сингулярное разложение второй исходной матрицы a2 (из первого задания). Вывести размер каждой из матриц

In [14]:
U, S, Vt = np.linalg.svd(a2)

In [15]:
print(U)
print(np.diag(S))
print(Vt)

[[-0.28768963  0.22140928  0.22176696 -0.3241351   0.38046537  0.37953633
   0.40906517 -0.04376658 -0.08156936 -0.49429073  0.07028532]
 [-0.3741815   0.289885   -0.58568544  0.26857216 -0.28518273  0.40668078
  -0.04251621  0.31984775 -0.05919355 -0.04254005  0.06822212]
 [-0.2237059   0.32389368  0.21640447 -0.02928062 -0.22318442  0.25365595
  -0.33007448 -0.66314523  0.26808114  0.18051686  0.17332941]
 [-0.21283283 -0.06145277  0.29185396  0.2159258  -0.05914448  0.16094267
  -0.2376383  -0.04116303 -0.35770798 -0.08012595 -0.77277482]
 [-0.25230411 -0.63087644  0.17756458  0.32299391  0.11914042  0.22175779
  -0.21257274  0.13148232  0.4258858  -0.23535695  0.19966464]
 [-0.33154016 -0.12595032 -0.48900566  0.00219217  0.61573831 -0.2383833
  -0.20201803 -0.35402771 -0.15286117  0.09071896 -0.03718424]
 [-0.4048688   0.0722972   0.27282278  0.52351081 -0.04069963 -0.31994433
   0.51546631 -0.06770239 -0.1302576   0.2485612   0.17116908]
 [-0.41536051  0.30910384  0.22068468 -0.2

6) Вычислить ранг у матриц a1 и a2

In [13]:
np.linalg.matrix_rank(a1)

6

In [16]:
np.linalg.matrix_rank(a2)

8

7) Вычислить собственные векторы и собственные значения матрицы - X_matrix

- np.linalg.eig(X_matrix) - для поиска собственных значений и собственных векторов матрицы - X_matrix

- Возвращает w и v, где w - собственные значения матрицы, v - собственные векторы матрицы

- Может вернуть несколько значений и векторов, тогда, чтобы посмотреть на один из вариантов:

w[0] соответствует v[:,0]

In [18]:
X_matrix = np.array([[-1, -6], [2, 6]])

w,v = np.linalg.eig(X_matrix)
print(w)
print(v)

[2. 3.]
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


8) Проверка:

- **Проверьте**, что при умножении матрицы X_matrix и 1го собственного вектора, получается тот же результат, что и при умножении 1го собственного значения и 1го собственного вектора
- **Сделайте аналогичные действия для других собственных значений** матрицы и векторов X_matrix

In [32]:
print(X_matrix @ v[:,0])
print(w[0] * v[:,0])b

[-1.78885438  0.89442719]
[-1.78885438  0.89442719]


In [43]:
print(X_matrix @ v[:,1])
print(w[1] * v[:,1])

[ 2.49615088 -1.66410059]
[ 2.49615088 -1.66410059]


9) Вам даны 2 вектора: a и b. Определите косинус угла между ними

In [38]:
a = np.array([2, 4, 5])
b = np.array([1, 3, 2])

np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

0.9561828874675148

10) Найдите манхэттенскую норму **векторов a и b из 9 задания**

In [41]:
np.linalg.norm(b-a, ord =1)

5.0

11) Найдите евклидову норму **векторов a и b из 9 задания**

In [42]:
np.linalg.norm(b-a,ord=2)

3.3166247903554